### PR TITLE
Create ThousandSons.yaml

### PR DESCRIPTION
**Pull request by Draxonfly**
Thousand Sons

### CODE REVIEW

**Comment by AppSynergy** [comment]
Rejected only because I'd rather keep the history fairly clean so I cherry picked it instead, there wasn't actual conflicts.

But in general, can you fast-forward your fork before submitting PRs please? Thanks!

**Comment by Draxonfly** [comment]
“can you fast-forward your fork before submitting PRs”
I don’t know what that means.. ??

**Comment by AppSynergy** [comment]
It means something like:

https://www.sitepoint.com/quick-tip-sync-your-fork-with-the-original-without-the-cli/

or if you're on the command line, `git pull` should do the job.

Or I think there's simply a "Sync" or "Fast forward" button, somewhere near where it says:

`This branch is 1 commit ahead, 56 commits behind AppSynergy:master.` on [your fork](https://github.com/Draxonfly/killteams.com).

**Comment by AppSynergy** [comment]
Honestly, it probably wouldn't have mattered, the point instead really is to fast-forward / sync before adding new stuff *(or at least realize you could be looking at out of date files)*. If it doesn't bite you in the ass now, it will later!

**Pull request closed without merging**
